//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    static func AdminGetModerationEvent(client: any XRPCClientProtocol, id: Int) async throws -> AdminDefs_ModEventViewDetail {
        let params: Parameters = ["id": .integer(id)]
        return try await client.fetch(endpoint: "com.atproto.admin.getModerationEvent", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
