//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    static func AdminGetAccountInfo(client: any XRPCClientProtocol, did: String) async throws -> AdminDefs_AccountView {
        let params: Parameters = ["did": .string(did)]
        return try await client.fetch(endpoint: "com.atproto.admin.getAccountInfo", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
