//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class AdminUpdateAccountHandle_Input: Codable {
        var did: String
        var handle: String

        init(did: String, handle: String) {
            self.did = did
            self.handle = handle
        }

        enum CodingKeys: String, CodingKey {
            case did
            case handle
        }
    }

    static func AdminUpdateAccountHandle(client: any XRPCClientProtocol, input: AdminUpdateAccountHandle_Input) async throws -> Bool {
        let params: Bool? = nil
        return try await client.fetch(endpoint: "com.atproto.admin.updateAccountHandle", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
    }
}
