//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class AdminDeleteAccount_Input: Codable {
        var did: String

        init(did: String) {
            self.did = did
        }

        enum CodingKeys: String, CodingKey {
            case did
        }
    }

    static func AdminDeleteAccount(client: any XRPCClientProtocol, input: AdminDeleteAccount_Input) async throws -> Bool {
        let params: Bool? = nil
        return try await client.fetch(endpoint: "com.atproto.admin.deleteAccount", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
    }
}
