//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class IdentityUpdateHandle_Input: Codable {
        var handle: String

        init(handle: String) {
            self.handle = handle
        }

        enum CodingKeys: String, CodingKey {
            case handle
        }
    }

    static func IdentityUpdateHandle(client: any XRPCClientProtocol, input: IdentityUpdateHandle_Input) async throws -> Bool {
        let params: Bool? = nil
        return try await client.fetch(endpoint: "com.atproto.identity.updateHandle", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
    }
}
