//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class LabelSubscribeLabels_Info: Codable {
        var message: String?
        var name: String

        init(message: String?, name: String) {
            self.message = message
            self.name = name
        }

        enum CodingKeys: String, CodingKey {
            case message
            case name
        }
    }

    class LabelSubscribeLabels_Labels: Codable {
        var labels: [LabelDefs_Label]
        var seq: Int

        init(labels: [LabelDefs_Label], seq: Int) {
            self.labels = labels
            self.seq = seq
        }

        enum CodingKeys: String, CodingKey {
            case labels
            case seq
        }
    }
}
