//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class RepoUploadBlob_Output: Codable {
        var blob: LexBlob

        init(blob: LexBlob) {
            self.blob = blob
        }

        enum CodingKeys: String, CodingKey {
            case blob
        }
    }

    static func RepoUploadBlob(client: any XRPCClientProtocol, input: Data) async throws -> RepoUploadBlob_Output {
        let params: Bool? = nil
        return try await client.fetch(endpoint: "com.atproto.repo.uploadBlob", contentType: "*/*", httpMethod: .post, params: params, input: input, retry: true)
    }
}
