//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class ServerRequestEmailUpdate_Output: Codable {
        var tokenRequired: Bool

        init(tokenRequired: Bool) {
            self.tokenRequired = tokenRequired
        }

        enum CodingKeys: String, CodingKey {
            case tokenRequired
        }
    }

    static func ServerRequestEmailUpdate(client: any XRPCClientProtocol) async throws -> ServerRequestEmailUpdate_Output {
        let params: Bool? = nil
        return try await client.fetch(endpoint: "com.atproto.server.requestEmailUpdate", contentType: "*/*", httpMethod: .post, params: params, input: Bool?.none, retry: true)
    }
}
