//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class ServerGetAccountInviteCodes_Output: Codable {
        var codes: [ServerDefs_InviteCode]

        init(codes: [ServerDefs_InviteCode]) {
            self.codes = codes
        }

        enum CodingKeys: String, CodingKey {
            case codes
        }
    }

    static func ServerGetAccountInviteCodes(client: any XRPCClientProtocol, createAvailable: Bool?, includeUsed: Bool?) async throws -> ServerGetAccountInviteCodes_Output {
        let params: Parameters = ["createAvailable": .bool(createAvailable), "includeUsed": .bool(includeUsed)]
        return try await client.fetch(endpoint: "com.atproto.server.getAccountInviteCodes", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
