//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class ServerRevokeAppPassword_Input: Codable {
        var name: String

        init(name: String) {
            self.name = name
        }

        enum CodingKeys: String, CodingKey {
            case name
        }
    }

    static func ServerRevokeAppPassword(client: any XRPCClientProtocol, input: ServerRevokeAppPassword_Input) async throws -> Bool {
        let params: Bool? = nil
        return try await client.fetch(endpoint: "com.atproto.server.revokeAppPassword", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
    }
}
