//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    static func SyncGetBlob(client: any XRPCClientProtocol, cid: String, did: String) async throws -> Data {
        let params: Parameters = ["cid": .string(cid), "did": .string(did)]
        return try await client.fetch(endpoint: "com.atproto.sync.getBlob", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
