//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class SyncGetLatestCommit_Output: Codable {
        var cid: String
        var rev: String

        init(cid: String, rev: String) {
            self.cid = cid
            self.rev = rev
        }

        enum CodingKeys: String, CodingKey {
            case cid
            case rev
        }
    }

    static func SyncGetLatestCommit(client: any XRPCClientProtocol, did: String) async throws -> SyncGetLatestCommit_Output {
        let params: Parameters = ["did": .string(did)]
        return try await client.fetch(endpoint: "com.atproto.sync.getLatestCommit", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
