//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    static func SyncGetBlocks(client: any XRPCClientProtocol, cids: [String], did: String) async throws -> Data {
        let params: Parameters = ["cids": .array(cids), "did": .string(did)]
        return try await client.fetch(endpoint: "com.atproto.sync.getBlocks", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
