//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    static func SyncGetRecord(client: any XRPCClientProtocol, collection: String, commit: String?, did: String, rkey: String) async throws -> Data {
        let params: Parameters = ["collection": .string(collection), "commit": .string(commit), "did": .string(did), "rkey": .string(rkey)]
        return try await client.fetch(endpoint: "com.atproto.sync.getRecord", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
