//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    static func SyncGetRepo(client: any XRPCClientProtocol, did: String, since: String?) async throws -> Data {
        let params: Parameters = ["did": .string(did), "since": .string(since)]
        return try await client.fetch(endpoint: "com.atproto.sync.getRepo", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
