//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    class SyncGetHead_Output: Codable {
        var root: String

        init(root: String) {
            self.root = root
        }

        enum CodingKeys: String, CodingKey {
            case root
        }
    }

    static func SyncGetHead(client: any XRPCClientProtocol, did: String) async throws -> SyncGetHead_Output {
        let params: Parameters = ["did": .string(did)]
        return try await client.fetch(endpoint: "com.atproto.sync.getHead", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
