//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension comatprototypes {
    static func TempImportRepo(client: any XRPCClientProtocol, input: Data, did: String) async throws -> String {
        let params: Parameters = ["did": .string(did)]
        return try await client.fetch(endpoint: "com.atproto.temp.importRepo", contentType: "*/*", httpMethod: .post, params: params, input: input, retry: true)
    }
}
