//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    class ActorPutPreferences_Input: Codable {
        var preferences: [ActorDefs_Preferences_Elem]

        init(preferences: [ActorDefs_Preferences_Elem]) {
            self.preferences = preferences
        }

        enum CodingKeys: String, CodingKey {
            case preferences
        }
    }

    static func ActorPutPreferences(client: any XRPCClientProtocol, input: ActorPutPreferences_Input) async throws -> Bool {
        let params: Bool? = nil
        return try await client.fetch(endpoint: "app.bsky.actor.putPreferences", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
    }
}
