//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto

enum appbskytypes {
    static func registerLexiconTypes() {
        LexiconTypesMap.shared.register(id: "app.bsky.actor.profile", val: ActorProfile.self)
        LexiconTypesMap.shared.register(id: "app.bsky.feed.generator", val: FeedGenerator.self)
        LexiconTypesMap.shared.register(id: "app.bsky.feed.like", val: FeedLike.self)
        LexiconTypesMap.shared.register(id: "app.bsky.feed.post", val: FeedPost.self)
        LexiconTypesMap.shared.register(id: "app.bsky.feed.repost", val: FeedRepost.self)
        LexiconTypesMap.shared.register(id: "app.bsky.feed.threadgate", val: FeedThreadgate.self)
        LexiconTypesMap.shared.register(id: "app.bsky.graph.block", val: GraphBlock.self)
        LexiconTypesMap.shared.register(id: "app.bsky.graph.follow", val: GraphFollow.self)
        LexiconTypesMap.shared.register(id: "app.bsky.graph.list", val: GraphList.self)
        LexiconTypesMap.shared.register(id: "app.bsky.graph.listblock", val: GraphListblock.self)
        LexiconTypesMap.shared.register(id: "app.bsky.graph.listitem", val: GraphListitem.self)
    }
}
