//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    class EmbedExternal: Codable {
        var external: EmbedExternal_External

        init(external: EmbedExternal_External) {
            self.external = external
        }

        enum CodingKeys: String, CodingKey {
            case external
        }
    }

    class EmbedExternal_External: Codable {
        var description: String
        var thumb: LexBlob?
        var title: String
        var uri: String

        init(description: String, thumb: LexBlob?, title: String, uri: String) {
            self.description = description
            self.thumb = thumb
            self.title = title
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case description
            case thumb
            case title
            case uri
        }
    }

    class EmbedExternal_View: Codable {
        var external: EmbedExternal_ViewExternal

        init(external: EmbedExternal_ViewExternal) {
            self.external = external
        }

        enum CodingKeys: String, CodingKey {
            case external
        }
    }

    class EmbedExternal_ViewExternal: Codable {
        var description: String
        var thumb: String?
        var title: String
        var uri: String

        init(description: String, thumb: String?, title: String, uri: String) {
            self.description = description
            self.thumb = thumb
            self.title = title
            self.uri = uri
        }

        enum CodingKeys: String, CodingKey {
            case description
            case thumb
            case title
            case uri
        }
    }
}
