//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    class FeedGetPosts_Output: Codable {
        var posts: [FeedDefs_PostView]

        init(posts: [FeedDefs_PostView]) {
            self.posts = posts
        }

        enum CodingKeys: String, CodingKey {
            case posts
        }
    }

    static func FeedGetPosts(client: any XRPCClientProtocol, uris: [String]) async throws -> FeedGetPosts_Output {
        let params: Parameters = ["uris": .array(uris)]
        return try await client.fetch(endpoint: "app.bsky.feed.getPosts", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
