//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    class FeedGetFeedGenerators_Output: Codable {
        var feeds: [FeedDefs_GeneratorView]

        init(feeds: [FeedDefs_GeneratorView]) {
            self.feeds = feeds
        }

        enum CodingKeys: String, CodingKey {
            case feeds
        }
    }

    static func FeedGetFeedGenerators(client: any XRPCClientProtocol, feeds: [String]) async throws -> FeedGetFeedGenerators_Output {
        let params: Parameters = ["feeds": .array(feeds)]
        return try await client.fetch(endpoint: "app.bsky.feed.getFeedGenerators", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
