//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    class GraphMuteActorList_Input: Codable {
        var list: String

        init(list: String) {
            self.list = list
        }

        enum CodingKeys: String, CodingKey {
            case list
        }
    }

    static func GraphMuteActorList(client: any XRPCClientProtocol, input: GraphMuteActorList_Input) async throws -> Bool {
        let params: Bool? = nil
        return try await client.fetch(endpoint: "app.bsky.graph.muteActorList", contentType: "application/json", httpMethod: .post, params: params, input: input, retry: true)
    }
}
