//
// DO NOT EDIT
//
// Generated by swift-atproto
//

import SwiftAtproto
import Foundation

extension appbskytypes {
    class UnspeccedGetPopularFeedGenerators_Output: Codable {
        var cursor: String?
        var feeds: [FeedDefs_GeneratorView]

        init(cursor: String?, feeds: [FeedDefs_GeneratorView]) {
            self.cursor = cursor
            self.feeds = feeds
        }

        enum CodingKeys: String, CodingKey {
            case cursor
            case feeds
        }
    }

    static func UnspeccedGetPopularFeedGenerators(client: any XRPCClientProtocol, cursor: String?, limit: Int?, query: String?) async throws -> UnspeccedGetPopularFeedGenerators_Output {
        let params: Parameters = ["cursor": .string(cursor), "limit": .integer(limit), "query": .string(query)]
        return try await client.fetch(endpoint: "app.bsky.unspecced.getPopularFeedGenerators", contentType: "*/*", httpMethod: .get, params: params, input: Bool?.none, retry: true)
    }
}
